language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang

install:
  - bash .travis_install.sh
 
branches:
  only:
  - develop

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCGOGN_BUILD_TESTS=ON -DCGOGN_BUILD_EXAMPLES=ON
  - make
  - make test
