
language: cpp

os:
  - linux
  - osx

#compiler:
#  - g++
#  - clang

#matrix:
#  include:
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx

before_install:
  - bash .travis_install.sh
    
branches:
  only:
#  - develop
  - sylvain

script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  cmake .. -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCGOGN_BUILD_TESTS=ON -DCGOGN_BUILD_EXAMPLES=ON ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  cmake .. -DCGOGN_MODULE_rendering=OFF -DCGOGN_USE_QT=OFF -DCGOGN_BUILD_TESTS=ON -DCGOGN_BUILD_EXAMPLES=ON ; fi
  - make
  - make test
